# Generated by Django 4.2.6 on 2023-11-08 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('category1', models.CharField(max_length=20)),
                ('category2', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(max_length=20)),
                ('category2', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
    ]
